version: '3.3'
services:
  mysql-db:
    build: ./db/docker
    restart: always
    environment:
      ACCEPT_EULA: "Y"
      SA_PASSWORD: HelloW0rld
      MSSQL_DB: Todoit
    ports:
      - 33500:1433
  application:
    image: nadiamiteva/mysqlserver-db
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    depends_on:
      - mysql-db
    ports:
      - 33400:80
  flyway:
    image: flyway/flyway
    command: migrate
    volumes:
      - ./db:/flyway/sql
      - ./db:/flyway/conf
    depends_on:
      - mysql-db